>>> def f(a, b, c=5, d=[1,3]):
...     print a, b, c, d
... 
>>> f(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: f() takes at least 2 arguments (1 given)
>>> f(1, 2)
1 2 5 [1, 3]
>>> f(1, 2, 'c')
1 2 c [1, 3]
>>> f(1, 2, d='D', c='C')
1 2 C D
>>> def f(a, b, *args):
...     print a, b, 
...     for x in args:
...         print x,
... 
>>> f(1, 2)
1 2
>>> f(1, 2, 3, 4, 5, 6)
1 2 3 4 5 6
>>> 
